version: '3'
services:
  app:
    build: ./app
    container_name: web_app
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=myapp_db
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
      - ./logs/mysql:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app_network

  # firewall:
  #   build: ./firewall 
  #   container_name: ufw_container
  #   network_mode: host
  #   privileged: true
  #   volumes:
  #     - ./logs/firewall:/var/log/ufw
  #     - ./firewall/ufw.conf:/etc/ufw/ufw.conf

  # ids:
  #   build: ./ids
  #   container_name: suricata_container
  #   network_mode: host
  #   privileged: true
  #   volumes:
  #     - ./logs/suricata:/var/log/suricata

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
